//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyClass_wcf.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyDisk")]
    public interface IMyDisk {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyDisk/FreeSpace", ReplyAction="http://tempuri.org/IMyDisk/FreeSpaceResponse")]
        string FreeSpace(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyDisk/FreeSpace", ReplyAction="http://tempuri.org/IMyDisk/FreeSpaceResponse")]
        System.Threading.Tasks.Task<string> FreeSpaceAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyDisk/TotalSpace", ReplyAction="http://tempuri.org/IMyDisk/TotalSpaceResponse")]
        string TotalSpace(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyDisk/TotalSpace", ReplyAction="http://tempuri.org/IMyDisk/TotalSpaceResponse")]
        System.Threading.Tasks.Task<string> TotalSpaceAsync(string obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyDiskChannel : ProxyClass_wcf.ServiceReference1.IMyDisk, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyDiskClient : System.ServiceModel.ClientBase<ProxyClass_wcf.ServiceReference1.IMyDisk>, ProxyClass_wcf.ServiceReference1.IMyDisk {
        
        public MyDiskClient() {
        }
        
        public MyDiskClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyDiskClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyDiskClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyDiskClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string FreeSpace(string obj) {
            return base.Channel.FreeSpace(obj);
        }
        
        public System.Threading.Tasks.Task<string> FreeSpaceAsync(string obj) {
            return base.Channel.FreeSpaceAsync(obj);
        }
        
        public string TotalSpace(string obj) {
            return base.Channel.TotalSpace(obj);
        }
        
        public System.Threading.Tasks.Task<string> TotalSpaceAsync(string obj) {
            return base.Channel.TotalSpaceAsync(obj);
        }
    }
}
